Задание 2. Добавлен README.md
gpb-it-factory/khabibullin-telergam-bot pull request #3
Opened 2024-05-14 11:15 UTC by DusynHub

2024-05-15 04:53 UTC, vaganov-vadim requested changes
В целом всё здорово, сделал пару пометок - можно немного добавить и будет супер.

2024-05-15 04:53 UTC, vaganov-vadim commented on README.md
> +## Практический проект
Привет! Давай напишем, что конкретно в этом репозитории будет храниться, зачем он нужен.

2024-05-15 04:53 UTC, vaganov-vadim commented on README.md
> +    <details>
Предлагаю потренироваться с PlantUML и нарисовать похожую схемку. Да, так тоже можно, но в учебных целях давай попробуем новую для себя нотацию :)

2024-05-15 21:45 UTC, DusynHub commented on README.md
> +## Практический проект
Добавил описание

2024-05-15 21:45 UTC, DusynHub commented on README.md
> +    <details>
PlantUml в виде плагина не обрабатывает схему корректно, поэтому добавил схему и виде изображения

2024-05-17 05:43 UTC, vaganov-vadim commented on README.md
> +## Практический проект
Я имел в виду чуть больше именно текстового описания, а не само название :) Но так тоже можно!

2024-05-17 05:44 UTC, vaganov-vadim approved these changes
Аппруваю, но давай в фоне разберёмся с плагином PlantUML. Рендерить картинку - не самый хороший подход, ведь надо будет это делать при каждом  изменении.

2024-05-17 07:41 UTC, merged